// pages/_app.js or src/app/layout.js

import { Inter } from "next/font/google";
import "@/shared/styles/globals.css";
import Providers from "@/shared/utils/Provider";
import localFont from "next/font/local"; // Note the correct import path

const clashDisplay = localFont({
  src: '../assets/fonts/ClashDisplay-Variable.ttf',
  variable: '--font-clashDisplay',
  weight: '700'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
